lostinthewoods/Models/Trail.cs
using System.ComponentModel.DataAnnotations;
 
namespace lostinthewoods.Models
{
    public abstract class BaseEntity {}
    public class Trail : BaseEntity
    {
        [Key]
        public int id { get; set; }

        [Required]
        [MinLength(1, ErrorMessage="Name field is required")]
        public string name { get; set; }

        [Required]
        [MinLength(10, ErrorMessage="Description must be at least 10 characters")]
        public string description { get; set; }

        [Required(ErrorMessage = "Length field is required")]
        public float length { get; set; }
 
        [Required(ErrorMessage = "Elevation change field is required")]
        public int elevation { get; set; }
 
        [Required(ErrorMessage = "Longitude field is required")]
        public string longitude { get; set; }

        [Required(ErrorMessage = "Latitude field is required")]
        public string latitude { get; set; }
    }
}

lostinthewoods/Controllers/TrailController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using lostinthewoods.Models;
using lostinthewoods.Factory;

namespace lostinthewoods.Controllers
{
    public class TrailController : Controller
    {
        private readonly TrailFactory trailFactory;
        public TrailController(TrailFactory _trailfactory)
        {
            trailFactory = _trailfactory;
        }


        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            ViewBag.allTrails = trailFactory.FindAll();
            return View();
        }


        [HttpGet]
        [Route("addTrail")]
        public IActionResult AddTrail()
        {
            
            return View("newtrail");
        }


        [HttpPost]
        [Route("createTrail")]
        public IActionResult createTrail(Trail trail)
        {
            if(ModelState.IsValid)
            {
                trailFactory.Add(trail);
                System.Console.WriteLine("Trail successfully added to DB");
                return RedirectToAction("Index");
            }
            System.Console.WriteLine("*/*/*/* Failed to create new trail */*/*/*");
            return View("newtrail");
        }

        [HttpGet]
        [Route("trails/{id}")]  
        public IActionResult viewTrail(int id)
        {
            ViewBag.trail = trailFactory.FindByID(id);
            return View("trailinfo");
        }
    }
}

lostinthewoods/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lostinthewoods</title>
    
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
        
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        
        
        <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

lostinthewoods/Views/Trail/Index.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>

        <h1>Lost in the Woods!</h1>
        @{
        <table class="table">
            <thead>
                <th>Trail Name &nbsp;</th>
                <th>Trail Length (miles) &nbsp;</th>
                <th>Elevation Change (feet) &nbsp;</th>
            </thead>
                @foreach(var t in ViewBag.allTrails)
                {
                <tr>
                    <td><a href="trails/@t.id">@t.name</a></td>
                    <td>@t.length</td>
                    <td>@t.elevation</td>
                </tr>
                }
        </table>
        }
        <br><br><br>
        <a href="/addTrail"><button class="btn btn-info">Add a trail</button></a>


    </body>
</html>

lostinthewoods/Views/Trail/newtrail.cshtml
@model lostinthewoods.Models.Trail

<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <br>
        <a href="/"><button class="btn btn-info">Home</button></a>
        <br>
        <h1>Add a new Trail!</h1>
        <form asp-controller="Trail" asp-action="createTrail" method="POST">
            <span asp-validation-for="name"></span>
            <input class="form-control" placeholder="Trail Name" asp-for="name">

            <span asp-validation-for="description"></span>
            <input class="form-control" placeholder="Description" asp-for="description">

            <span asp-validation-for="length"></span>
            <input class="form-control" placeholder="Length (miles)" asp-for="length">

            <span asp-validation-for="elevation"></span>
            <input class="form-control" placeholder="Elevation Change (feet)" asp-for="elevation">

            <span asp-validation-for="latitude"></span>
            <input class="form-control" placeholder="Latitude" asp-for="latitude">

            <span asp-validation-for="longitude"></span>
            <input class="form-control" placeholder="Longitude" asp-for="longitude">


            <button class="btn btn-info" type="submit">Create</button>
        </form>


    </body>
</html>

lostinthewoods/Views/Trail/trailinfo.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>

        <h2>@ViewBag.trail.name</h2>
        <h3>Description: @ViewBag.trail.description</h3>
        <h3>Trail Length: @ViewBag.trail.length</h3>
        <h3>Elevation Change: @ViewBag.trail.elevation</h3>
<br><br>
<a href="/"><button class="btn btn-info">Home</button></a>
    </body>
</html>