dojoleague/Models/Dojo.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
 
namespace dojoleague.Models
{
    public abstract class BaseEntity {}
    public class Dojo : BaseEntity
    {
        [Key]
        public long iddojo { get; set; }


        [Required]
        [MinLength(2, ErrorMessage="Dojo name must be at least 2 characters long")]
        public string name { get; set; }

        [Required]
        [MinLength(3, ErrorMessage="Location must be at least 3 characters long")]
        public string location { get; set; }


        [Required(ErrorMessage = "Length field is required")]
        public string info { get; set; }
        
        public ICollection<Ninja> ninjas { get; set; }
 
    }
}

dojoleague/Models/Ninja.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
 
namespace dojoleague.Models
{
    public class Ninja : BaseEntity
    {
        [Key]
        public long idninja { get; set; }


        [Required]
        [MinLength(2, ErrorMessage="Ninja name must be at least 2 characters long")]
        public string name { get; set; }

        [Required(ErrorMessage="Level required")]
        public int level { get; set; }

        [Required(ErrorMessage = "Description field is required")]
        public string description { get; set; }
        public Dojo dojo { get; set; }
    }
}

dojoleague/Controllers/DojoController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using dojoleague.Models;
using dojoleague.Factory;

namespace dojoleague.Controllers
{
    public class DojoController : Controller
    {
        private readonly DojoFactory dojoFactory;
        public DojoController(DojoFactory _dojofactory)
        {
            dojoFactory = _dojofactory;
        }


        [HttpGet]
        [Route("dojos")]
        public IActionResult Index()
        {
            ViewBag.allDojos = dojoFactory.FindAll();
            return View("dojos");
        }


        [HttpPost]
        [Route("createDojo")]
        public IActionResult createDojo(Dojo dojo)
        {
            if(ModelState.IsValid)
            {
                dojoFactory.Add(dojo);
                return RedirectToAction("Index");
            }
            return View("newtrail");
        } 

        [HttpGet]
        [Route("dojos/{id}")]  
        public IActionResult viewDojo(int id)
        {
            ViewBag.dojo = dojoFactory.FindByID(id);
            return View("dojoinfo");
        }
    }
}

dojoleague/Controllers/NinjaController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using dojoleague.Models;
using dojoleague.Factory;

namespace dojoleague.Controllers
{
    public class NinjaController : Controller
    {
        private readonly NinjaFactory ninjaFactory;
        public NinjaController(NinjaFactory _ninjafactory)
        {
            ninjaFactory = _ninjafactory;
        }


        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            ViewBag.allNinjas = ninjaFactory.FindAll();
            return View("ninjas");
        }


        [HttpPost]
        [Route("registerNinja")]
        public IActionResult registerNinja(Ninja ninja)
        {
            if(ModelState.IsValid)
            {
                ninjaFactory.Add(ninja);
                return RedirectToAction("ninjas");
            }
            return View("ninjainfo");
        } 
        [HttpGet]
        [Route("ninjas/{id}")]  
        public IActionResult viewTrail(int id)
        {
            ViewBag.ninja = ninjaFactory.FindByID(id);
            return View("ninjainfo");
        }
    }
}

dojoleague/Views/Ninja/ninjas.cshtml
@model dojoleague.Models.Ninja
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <div id="registeredNinjas">
            <h1>Registered Ninjas</h1>
            <table class="table">
                <thead>
                    <th>Ninja Name</th>
                    <th>Home Dojo</th>
                </thead>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
        <br>
        <br>
        <div id="registerANinja">
            <h1>Register a Ninja</h1>
            <form asp-controller="Ninja" asp-action="registerNinja" method="POST">
                <span asp-validation-for="name"></span>
                <input placeholder="Ninja Name" asp-for="name"><br>

                <span asp-validation-for="level"></span>
                <input placeholder="Level" asp-for="level"><br>

                <span asp-validation-for="description"></span>
                <input placeholder="Description" asp-for="description"><br>

                <span asp-validation-for="dojos_id"></span>
                <select asp-for="dojos_id" class="form-control">
                    <option value="0">Rogue</option>
                @{
                    @foreach(var dojo in ViewBag.allDojos)
                    {
                        <option value="@dojo.id">@dojo.name</option>
                    }
                }
                </select>

                <button value="submit" class="btn btn-info">Register</button><br>
            </form>
        </div>
        <br>

            <a href="/dojos"><button>View Dojos</button></a>

    </body>
</html>

dojoleague/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dojoleague</title>
    
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
        
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">
        </script>
        
        
        <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>